# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connectwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(315, 206)
        self.iplabel = QtWidgets.QLabel(Form)
        self.iplabel.setGeometry(QtCore.QRect(30, 30, 31, 16))
        self.iplabel.setObjectName("iplabel")
        self.portlabel = QtWidgets.QLabel(Form)
        self.portlabel.setGeometry(QtCore.QRect(30, 70, 41, 16))
        self.portlabel.setObjectName("portlabel")
        self.ipplaintextedit = QtWidgets.QPlainTextEdit(Form)
        self.ipplaintextedit.setGeometry(QtCore.QRect(90, 20, 191, 31))
        self.ipplaintextedit.setObjectName("ipplaintextedit")
        self.portplaintextedit = QtWidgets.QPlainTextEdit(Form)
        self.portplaintextedit.setGeometry(QtCore.QRect(90, 70, 191, 31))
        self.portplaintextedit.setObjectName("portplaintextedit")
        self.connectbutton = QtWidgets.QPushButton(Form)
        self.connectbutton.setGeometry(QtCore.QRect(30, 140, 113, 32))
        self.connectbutton.setObjectName("connectbutton")
        self.cancelbutton = QtWidgets.QPushButton(Form)
        self.cancelbutton.setGeometry(QtCore.QRect(170, 140, 113, 32))
        self.cancelbutton.setObjectName("cancelbutton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.iplabel.setText(_translate("Form", "IP"))
        self.portlabel.setText(_translate("Form", "PORT"))
        self.connectbutton.setText(_translate("Form", "connect"))
        self.cancelbutton.setText(_translate("Form", "cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
