# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets # 위젯 클래스들

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(744, 526)
        self.htmlbrowser = QtWidgets.QTextBrowser(Form)
        self.htmlbrowser.setGeometry(QtCore.QRect(10, 10, 551, 211))
        self.htmlbrowser.setObjectName("htmlbrowser")
        self.logbutton = QtWidgets.QTextBrowser(Form)
        self.logbutton.setGeometry(QtCore.QRect(10, 230, 551, 181))
        self.logbutton.setObjectName("logbutton")
        self.openGLWidget = QtWidgets.QOpenGLWidget(Form)
        self.openGLWidget.setGeometry(QtCore.QRect(10, 420, 551, 91))
        self.openGLWidget.setObjectName("openGLWidget")
        self.databutton = QtWidgets.QPushButton(Form)
        self.databutton.setGeometry(QtCore.QRect(570, 40, 171, 31))
        self.databutton.setObjectName("databutton")
        self.dataanalysisbutton = QtWidgets.QPushButton(Form)
        self.dataanalysisbutton.setGeometry(QtCore.QRect(570, 70, 171, 31))
        self.dataanalysisbutton.setObjectName("dataanalysisbutton")
        self.seebutton = QtWidgets.QPushButton(Form)
        self.seebutton.setGeometry(QtCore.QRect(570, 100, 171, 31))
        self.seebutton.setObjectName("seebutton")
        self.cachebutton = QtWidgets.QPushButton(Form)
        self.cachebutton.setGeometry(QtCore.QRect(570, 10, 171, 31))
        self.cachebutton.setObjectName("cachebutton")
        self.exitbutton = QtWidgets.QPushButton(Form)
        self.exitbutton.setGeometry(QtCore.QRect(570, 480, 171, 31))
        self.exitbutton.setObjectName("exitbutton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.databutton.setText(_translate("Form", "data recever"))
        self.dataanalysisbutton.setText(_translate("Form", "data analysis"))
        self.seebutton.setText(_translate("Form", "see datamap"))
        self.cachebutton.setText(_translate("Form", "cache clear"))
        self.exitbutton.setText(_translate("Form", "exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
