#FIX Request
FROM ubuntu:18.04

#kubeadm
RUN apt update && apt install -y apt-transport-https curl
RUN sudo curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add - 
RUN car << EOF | sudo tee /etc/apt/sources.list.d/kubernetes.list
RUN sudo apt update
RUN sudo apt install -y kube=1.18.15-00 kubeadm=1.18.15-00 kubectl=1.18.15-00 docker.io
RUN sudo apt-mark hold kubelet kebadm kubectl docker.io
RUN cat << EOF | sudo tee /etc/sysctl.d/k8s.conf
RUN sudo sysctl --system

# #image setup
# #WORKDIR /home/node
# #COPY entrypoint.sh run.sh
# #RUN chmod 774 run.sh

# #container setup
# # ENTRYPOINT [ "./run.sh" ]
# ENTRYPOINT [ "sudo kubeadm init \ --kubernets-version=1.18.15 \ --pod-network-cidr=172.31.0.0/16", "sudo kubeadm join 172.31.2.189:6443 --token zpn5s6." ]

# #commands to be executed when the container is running
# # CMD []

# #flannel network
# RUN kubectl apply -f \
#     https://raw.githubusercontent.com/cores/flannel/master/Documentation/kube-flaneel.yml

#move the pre-written scripts to the folder where the script is executed when the container is created in the Docker environment.
#COPY ./copyfile/ /copyfile/



#labe
#LABEL js@cleancode.kr

#container creation & execution command
#docker run --name [CONTAINER_NAME] -v $(pwd):/home/node [IMAGE_NAME]

#docker log view 
#docker logs -f [CONTAINER_NAME]